device : torch.device("cuda:0")
batch_size : 256
class_n : len(label_encoder)
learning_rate : 1e-4
embedding_dim : 512
num_features : len(csv_feature_dict)
max_len : 144
dropout_rate : 0.1
epochs : 10
vision_pretrain : True
save_path : 'best_model.pt'